// context private
export const INITIAL_CONTEXT = {
  elementsPossible: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p'],
  elementsActive: [
    {
      element: 'h1',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '48px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'p',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '16px',
        fontWeight: 'regular',
        lineHeight: '1.5',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
  ],
  elementsDefault: [
    {
      element: 'p',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '16px',
        fontWeight: 'regular',
        lineHeight: '1.5',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h1',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '48px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h2',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '32px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h3',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '24px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h4',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '20px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h5',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '18px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
    {
      element: 'h6',
      style: {
        color: '#fff',
        fontFamily: 'sans-serif',
        fontSize: '16px',
        fontWeight: 'regular',
        lineHeight: '1.2',
        marginBottom: '0',
        marginTop: '0',
      },
      text: 'Lorem ipsum dolor sit amet',
      verticalRhythmOverrides: {
        fontSize: null,
        lineHeight: null,
        marginBottom: null,
        marginTop: null,
      },
    },
  ],
  fontsPossible: ['Loading...'],
  verticalRhythmEnabled: false,
}
